/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.*;
import javax.swing.*;
import java.awt.Color;
/**
 *
 * @author LENOVO
 */
public class Chess extends javax.swing.JFrame {
    /**
     * Creates new form Chess
     */
    public Chess() {
        initComponents();
        initVariables();
    }
        String Name = "";
        String pass = "";
        JTextField output;
        JTextField Name1 = new JTextField();
        JTextField pass1 = new JTextField();
        public void initVariables(){
            Name1 = Nam;
//            Name1.add(Nam);
            pass1 = pas;
            output = outtxt;
            output.setText("");
        }
        public void addVariablesNam(String s){
            Name = s;
        }
         public void addVariablespas(String s){
            pass = s;
        }
        public void isValidPassword(){
            if(Name.length() == 0 && pass.length() == 0){ 
                output.setText(" Enter Credentials");
                output.setBackground(Color.red);
            return;
            }
            if(Name.length() == 0){ 
                output.setText(" Enter Name");
                output.setBackground(Color.red);
            return;
            }
             String text = pass;
             String passw = text;
            HashMap<Character, String> hm = new HashMap<>();
            String ans = "abcdefghijklmnopqrstuvwxyz0123456789";
            String ans2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            String ans3 = "~`!@#$%^&*()_-+={[}]|\\:;\"'<,>.?/";
            for(int i =0; i<ans.length(); i++){
                hm.put(ans.charAt(i), ans);
            }
            for(int i =0; i<ans2.length(); i++){
                hm.put(ans2.charAt(i), ans2);
            }
            for(int i =0; i<ans3.length(); i++){
                hm.put(ans3.charAt(i), ans3);
            }
            int count1 = 0, count2 = 0, count3 =0;
            for(int i =0; i< passw.length(); i++){
                char ch = passw.charAt(i);
                if(hm.containsKey(ch)){
                    if(hm.get(ch) == "abcdefghijklmnopqrstuvwxyz0123456789" && count1 <1){
                        count1++;
                    }
                    if(hm.get(ch) == "ABCDEFGHIJKLMNOPQRSTUVWXYZ" && count2 <1){
                        count2++;
                    }
                    if(hm.get(ch) == "~`!@#$%^&*()_-+={[}]|\\:;\"'<,>.?/" && count3 <1){
                        count3++;
                    }
                }
            }
            int count = count1+count2+count3;
            if(count ==3 && passw.length() >=8){
                output.setText("Password is Strong");
                output.setBackground(Color.green);
            }
            else if(count == 3 && passw.length() < 8 || count ==2 && passw.length() >=8){
                 output.setText("Password is Medium");
                output.setBackground(Color.orange);
            }
            else if(count == 1 || count ==2){
                output.setText("Password is Weak");
                output.setBackground(Color.PINK);
            }
            else{
                 output.setText(" Recheck your Password");
                output.setBackground(Color.red);
            }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        pas = new javax.swing.JPasswordField();
        outtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        Nam.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        btn.setText("Enter");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        pas.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });

        outtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn)
                    .addComponent(Nam)
                    .addComponent(pas, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(outtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamActionPerformed

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_pasActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
         String c = Name1.getText();
        addVariablesNam(c);
        String a = pass1.getText();
        addVariablespas(a);
        isValidPassword();
    }//GEN-LAST:event_btnActionPerformed

    private void outtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nam;
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField outtxt;
    private javax.swing.JPasswordField pas;
    // End of variables declaration//GEN-END:variables
}
